#
# General information about this Curriculum Module
#
[onramp]
#
# Author's name
#
author = Jason Regina
#
# Brief title of the module
#
title = pi
#
# Brief description of the module
#
description = """
Test module to calculate pi using Riemann Sum.
"""

#
# Descriptions for any keys defined in onramp_uioptions that require them.
#
# If the key is not listed then no extra description is provided to the user.
# Only the key name will be listed, and possibly a description of the 
# specification requirements (e.g., "Must be an even integer between 2-1000").
#
[onramp_uioptions]

[[pi]]
elements = Number of rectangular elements
threads = Number of OpenMP threads
