top_srcdir   = /root/onramp/server/apache/httpd-2.4.23
top_builddir = /root/onramp/server/apache/httpd-2.4.23
srcdir       = /root/onramp/server/apache/httpd-2.4.23/modules/filters
builddir     = /root/onramp/server/apache/httpd-2.4.23/modules/filters
VPATH        = /root/onramp/server/apache/httpd-2.4.23/modules/filters

include $(top_srcdir)/build/special.mk

