# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 06:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='module_id',
            new_name='module',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='pce_id',
            new_name='pce',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='workspace_id',
            new_name='workspace',
        ),
    ]
