top_srcdir   = /root/onramp/server/apache/httpd-2.4.23
top_builddir = /root/onramp/server/apache/httpd-2.4.23
srcdir       = /root/onramp/server/apache/httpd-2.4.23/modules/http
builddir     = /root/onramp/server/apache/httpd-2.4.23/modules/http
VPATH        = /root/onramp/server/apache/httpd-2.4.23/modules/http

include $(top_srcdir)/build/special.mk

