top_srcdir   = /root/onramp/server/apache/httpd-2.4.23
top_builddir = /root/onramp/server/apache/httpd-2.4.23
srcdir       = /root/onramp/server/apache/httpd-2.4.23/modules/aaa
builddir     = /root/onramp/server/apache/httpd-2.4.23/modules/aaa
VPATH        = /root/onramp/server/apache/httpd-2.4.23/modules/aaa

include $(top_srcdir)/build/special.mk

