top_srcdir   = /root/onramp/server/apache/httpd-2.4.23
top_builddir = /root/onramp/server/apache/httpd-2.4.23
srcdir       = /root/onramp/server/apache/httpd-2.4.23/server/mpm
builddir     = /root/onramp/server/apache/httpd-2.4.23/server/mpm
VPATH        = /root/onramp/server/apache/httpd-2.4.23/server/mpm

SUBDIRS = $(MPM_SUBDIRS)

include $(top_builddir)/build/rules.mk
