top_srcdir   = /root/onramp/server/apache/httpd-2.4.23
top_builddir = /root/onramp/server/apache/httpd-2.4.23
srcdir       = /root/onramp/server/apache/httpd-2.4.23/modules/dav/main
builddir     = /root/onramp/server/apache/httpd-2.4.23/modules/dav/main
VPATH        = /root/onramp/server/apache/httpd-2.4.23/modules/dav/main
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
