top_srcdir   = /root/onramp/server/apache/httpd-2.4.23
top_builddir = /root/onramp/server/apache/httpd-2.4.23
srcdir       = /root/onramp/server/apache/httpd-2.4.23/server/mpm/worker
builddir     = /root/onramp/server/apache/httpd-2.4.23/server/mpm/worker
VPATH        = /root/onramp/server/apache/httpd-2.4.23/server/mpm/worker

include $(top_srcdir)/build/special.mk
