top_srcdir   = /root/onramp/server/apache/httpd-2.4.23
top_builddir = /root/onramp/server/apache/httpd-2.4.23
srcdir       = /root/onramp/server/apache/httpd-2.4.23/modules/generators
builddir     = /root/onramp/server/apache/httpd-2.4.23/modules/generators
VPATH        = /root/onramp/server/apache/httpd-2.4.23/modules/generators

include $(top_srcdir)/build/special.mk

