top_srcdir   = /root/onramp/server/apache/httpd-2.4.23
top_builddir = /root/onramp/server/apache/httpd-2.4.23
srcdir       = /root/onramp/server/apache/httpd-2.4.23/modules/metadata
builddir     = /root/onramp/server/apache/httpd-2.4.23/modules/metadata
VPATH        = /root/onramp/server/apache/httpd-2.4.23/modules/metadata

include $(top_srcdir)/build/special.mk

