top_srcdir   = /root/onramp/server/apache/httpd-2.4.23
top_builddir = /root/onramp/server/apache/httpd-2.4.23
srcdir       = /root/onramp/server/apache/httpd-2.4.23/modules/arch/unix
builddir     = /root/onramp/server/apache/httpd-2.4.23/modules/arch/unix
VPATH        = /root/onramp/server/apache/httpd-2.4.23/modules/arch/unix

include $(top_srcdir)/build/special.mk

