top_srcdir   = /root/onramp/server/apache/httpd-2.4.23
top_builddir = /root/onramp/server/apache/httpd-2.4.23
srcdir       = /root/onramp/server/apache/httpd-2.4.23/os
builddir     = /root/onramp/server/apache/httpd-2.4.23/os
VPATH        = /root/onramp/server/apache/httpd-2.4.23/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
