top_srcdir   = /root/onramp/server/apache/httpd-2.4.23
top_builddir = /root/onramp/server/apache/httpd-2.4.23
srcdir       = /root/onramp/server/apache/httpd-2.4.23/modules/mappers
builddir     = /root/onramp/server/apache/httpd-2.4.23/modules/mappers
VPATH        = /root/onramp/server/apache/httpd-2.4.23/modules/mappers

include $(top_srcdir)/build/special.mk

