top_srcdir   = /root/onramp/server/apache/httpd-2.4.23
top_builddir = /root/onramp/server/apache/httpd-2.4.23
srcdir       = /root/onramp/server/apache/httpd-2.4.23/modules/loggers
builddir     = /root/onramp/server/apache/httpd-2.4.23/modules/loggers
VPATH        = /root/onramp/server/apache/httpd-2.4.23/modules/loggers

include $(top_srcdir)/build/special.mk

