top_srcdir   = /root/onramp/server/apache/httpd-2.4.23
top_builddir = /root/onramp/server/apache/httpd-2.4.23
srcdir       = /root/onramp/server/apache/httpd-2.4.23/modules/proxy/balancers
builddir     = /root/onramp/server/apache/httpd-2.4.23/modules/proxy/balancers
VPATH        = /root/onramp/server/apache/httpd-2.4.23/modules/proxy/balancers
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
